version: '3.9'
services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=ep_assemby_configurator_db
  #     - POSTGRES_USER=spp920677
  #     - POSTGRES_PASSWORD=spp920677
  #     - POSTGRES_HOST=a52a598eb70f
  #     - POSTGRES_PORT=5432
  web:
    build: .
    command: python3 manage.py runserver 127.0.0.1:8001
    ports:
      - "8001:8001"
    depends_on:
      - db
  db:
    image: postgres

    
    

