# Generated by Django 4.1.1 on 2022-10-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_pattern_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodeshopmapping',
            name='created_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='barcodeshopmapping',
            name='updated_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
