# Generated by Django 4.1.1 on 2022-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_twin_configure_app', '0002_delete_audit_delete_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmaster',
            name='name',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='stationmaster',
            name='number',
            field=models.CharField(max_length=110),
        ),
    ]
