# Generated by Django 4.1.1 on 2022-10-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_family_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partfamilytagcriticalitymapping',
            old_name='tag_criticality',
            new_name='tag_criticality_id',
        ),
    ]
