# Generated by Django 4.1.1 on 2022-10-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_twin_configure_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.DeleteModel(
            name='Barcode',
        ),
    ]
