# Generated by Django 4.1.1 on 2022-10-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodePatternMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code_type', models.IntegerField(null=True)),
                ('pattern_description', models.CharField(default='', max_length=500)),
                ('pattern_name', models.CharField(default='', max_length=250)),
                ('code_format', models.CharField(default='', max_length=250)),
                ('pattern_sample', models.CharField(default='', max_length=250)),
                ('pattern_length', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('part_number', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('part_number_start_at', models.IntegerField(blank=True, default='', null=True)),
                ('part_number_end_at', models.IntegerField(blank=True, default='', null=True)),
                ('vendor_code', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('vendor_code_start_at', models.IntegerField(blank=True, default='', null=True)),
                ('vendor_code_end_at', models.IntegerField(blank=True, default='', null=True)),
                ('batch_code', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('batch_code_start_at', models.IntegerField(blank=True, default='', null=True)),
                ('batch_code_end_at', models.IntegerField(blank=True, default='', null=True)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_by', models.CharField(default='', max_length=100)),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'barcode_pattern_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BarcodeShopMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('shop_type', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField()),
                ('barcode_pattern_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barcode_pattern_app.barcodepatternmaster')),
            ],
            options={
                'db_table': 'barcode_shop_mapping',
                'managed': True,
            },
        ),
    ]
