# Generated by Django 4.1.1 on 2022-10-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('part_family_name', models.CharField(default='', max_length=200)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_by', models.CharField(default='', max_length=100)),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'part_family',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TagCriticality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(default='', max_length=200)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_by', models.CharField(default='', max_length=100)),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'tag_criticality_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartFamilyTagCriticalityMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_by', models.CharField(default='', max_length=100)),
                ('updated_on', models.DateTimeField()),
                ('part_family_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='part_family_app.partfamily')),
                ('tag_criticality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='part_family_app.tagcriticality')),
            ],
            options={
                'db_table': 'part_family_tag_criticality_mapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartFamilyShopMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('shop_type', models.CharField(default='', max_length=150)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_by', models.CharField(default='', max_length=100)),
                ('updated_on', models.DateTimeField()),
                ('part_family_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='part_family_app.partfamily')),
            ],
            options={
                'db_table': 'part_family_shop_mapping',
                'managed': True,
            },
        ),
    ]
